<a href="https://colab.research.google.com/github/mnocerino23/NBA-Player-Classifier/blob/main/budgetPlayers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [92]:
import pandas as pd
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [93]:
complete = pd.read_csv('/content/drive/MyDrive/Data_Science_Projects/NBA/endSeasonCombined2022-2023.csv')

In [94]:
#limit our dataset to those who have played over 15 games this season
complete = complete.loc[complete['G'] > 15]

In [95]:
#450 players have played over 50 games this season
complete.shape

(450, 51)

# Who are the best bang for your buck players?

In [96]:
#add features price/offensive_win_share, price/defensive_win_share, price/win_share
#using lambda functions
complete = complete.assign(S_OWS =lambda x: (x['Salary']/x['OWS']))
complete = complete.assign(S_DWS =lambda x: (x['Salary']/x['DWS']))
complete = complete.assign(S_WS =lambda x: (x['Salary']/x['WS']))

In [97]:
complete.head(5)

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,WS,WS/48,OBPM,DBPM,BPM,VORP,Salary,S_OWS,S_DWS,S_WS
0,Precious Achiuwa,C,23,TOR,55,12,20.7,3.6,7.3,0.485,...,2.2,0.093,-1.4,-0.8,-2.3,-0.1,2.840160,3.550200,2.028686,1.290982
1,Steven Adams,C,29,MEM,42,42,27.0,3.7,6.3,0.597,...,3.4,0.144,-0.3,0.9,0.6,0.7,17.926829,13.789868,8.536585,5.272597
2,Bam Adebayo,C,25,MIA,75,75,34.6,8.0,14.9,0.540,...,7.4,0.137,0.8,0.8,1.5,2.3,30.351780,8.431050,7.987311,4.101592
3,Ochai Agbaji,SG,22,UTA,59,22,20.5,2.8,6.5,0.427,...,1.3,0.053,-1.7,-1.4,-3.0,-0.3,3.918360,4.353733,9.795900,3.014123
4,Santi Aldama,PF,22,MEM,77,20,21.8,3.2,6.8,0.470,...,4.6,0.130,-0.3,0.8,0.5,1.1,2.094120,0.997200,0.872550,0.455243

In [98]:
nonnegative_offense = complete.loc[(complete['OWS'] > 0) & (complete['Age'] >25) & (complete['PER'] >15)]
nonnegative_offense.nsmallest(10, ['S_OWS'])

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,WS,WS/48,OBPM,DBPM,BPM,VORP,Salary,S_OWS,S_DWS,S_WS
134,Kris Dunn,PG,28,UTA,22,3,25.8,5.3,9.8,0.537,...,1.9,0.162,0.7,1.7,2.4,0.6,0.735819,0.566015,1.226365,0.387273
273,Luke Kornet,C,27,BOS,69,0,11.7,1.6,2.5,0.665,...,3.3,0.198,-0.4,1.3,1.0,0.6,2.133278,1.015847,1.777732,0.646448
278,Jock Landale,C,27,PHO,69,4,14.2,2.6,4.9,0.528,...,2.7,0.132,-0.8,-0.4,-1.1,0.2,1.563518,1.042345,1.302932,0.579081
294,Kevon Looney,C,26,GSW,82,70,23.9,3.0,4.7,0.630,...,8.7,0.212,0.9,1.3,2.1,2.0,8.000000,1.355932,2.857143,0.919540
91,Brandon Clarke,PF,26,MEM,56,8,19.5,4.1,6.2,0.656,...,4.5,0.199,0.8,1.8,2.5,1.3,4.343920,1.608859,2.413289,0.965316
383,Mason Plumlee,C,32,TOT,79,60,26.0,4.2,6.1,0.680,...,7.9,0.185,1.2,1.0,2.2,2.2,9.080417,1.650985,3.783507,1.149420
191,Montrezl Harrell,C,29,PHI,57,7,11.9,2.2,3.7,0.598,...,2.2,0.153,-0.9,-0.4,-1.3,0.1,2.463490,1.894992,3.079363,1.119768
426,Domantas Sabonis,C,26,SAC,79,79,34.6,7.3,11.9,0.615,...,12.6,0.221,4.1,1.8,5.8,5.4,18.500000,1.927083,6.166667,1.468254
384,Jakob Poeltl,C,27,TOT,72,71,26.5,5.4,8.6,0.629,...,6.0,0.150,1.1,0.8,1.9,1.9,9.398148,2.540040,4.271885,1.566358
241,Cameron Johnson,PF,26,TOT,42,41,28.5,5.3,11.3,0.470,...,3.5,0.142,2.0,0.6,2.6,1.4,5.887899,2.803761,4.205642,1.682257

In [102]:
nonnegative_defense = complete.loc[(complete['DWS'] > 0) & (complete['Age'] >25) & (complete['PER'] >12)]
nonnegative_defense.nsmallest(10, ['S_DWS'])

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,WS,WS/48,OBPM,DBPM,BPM,VORP,Salary,S_OWS,S_DWS,S_WS
42,Bismack Biyombo,C,30,PHO,61,14,14.3,2.0,3.4,0.578,...,1.9,0.102,-3.4,2.5,-0.9,0.2,1.836090,9.180450,1.147556,0.966363
134,Kris Dunn,PG,28,UTA,22,3,25.8,5.3,9.8,0.537,...,1.9,0.162,0.7,1.7,2.4,0.6,0.735819,0.566015,1.226365,0.387273
302,Terance Mann,SG,26,LAC,81,36,23.1,3.4,6.5,0.519,...,4.3,0.111,-0.3,0.1,-0.2,0.8,1.930681,0.689529,1.287121,0.448996
278,Jock Landale,C,27,PHO,69,4,14.2,2.6,4.9,0.528,...,2.7,0.132,-0.8,-0.4,-1.1,0.2,1.563518,1.042345,1.302932,0.579081
519,Kenrich Williams,PF,28,OKC,53,10,22.8,3.4,6.5,0.517,...,3.3,0.133,0.1,0.4,0.5,0.8,2.000000,1.000000,1.538462,0.606061
131,Andre Drummond,C,29,CHI,67,0,12.7,2.5,4.1,0.606,...,2.8,0.159,-1.3,0.5,-0.8,0.3,3.200000,4.000000,1.600000,1.142857
332,Shake Milton,SG,26,PHI,76,11,20.6,3.2,6.6,0.479,...,2.9,0.087,-1.0,-0.9,-2.0,0.0,1.997718,1.248574,1.664765,0.688868
273,Luke Kornet,C,27,BOS,69,0,11.7,1.6,2.5,0.665,...,3.3,0.198,-0.4,1.3,1.0,0.6,2.133278,1.015847,1.777732,0.646448
122,Donte DiVincenzo,SG,26,GSW,72,36,26.3,3.3,7.5,0.435,...,4.2,0.106,-0.6,1.3,0.7,1.3,4.500000,2.368421,1.956522,1.071429
500,Yuta Watanabe,SF,28,BRK,58,1,16.0,2.0,4.0,0.491,...,2.1,0.111,-0.4,-0.2,-0.6,0.3,1.836090,1.412377,2.040100,0.874329

In [103]:
nonnegative_ws = complete.loc[(complete['WS'] > 0) & (complete['Age'] >25) & (complete['PER'] >12)]
nonnegative_ws.nsmallest(10, ['S_WS'])

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,WS,WS/48,OBPM,DBPM,BPM,VORP,Salary,S_OWS,S_DWS,S_WS
134,Kris Dunn,PG,28,UTA,22,3,25.8,5.3,9.8,0.537,...,1.9,0.162,0.7,1.7,2.4,0.6,0.735819,0.566015,1.226365,0.387273
302,Terance Mann,SG,26,LAC,81,36,23.1,3.4,6.5,0.519,...,4.3,0.111,-0.3,0.1,-0.2,0.8,1.930681,0.689529,1.287121,0.448996
278,Jock Landale,C,27,PHO,69,4,14.2,2.6,4.9,0.528,...,2.7,0.132,-0.8,-0.4,-1.1,0.2,1.563518,1.042345,1.302932,0.579081
519,Kenrich Williams,PF,28,OKC,53,10,22.8,3.4,6.5,0.517,...,3.3,0.133,0.1,0.4,0.5,0.8,2.000000,1.000000,1.538462,0.606061
273,Luke Kornet,C,27,BOS,69,0,11.7,1.6,2.5,0.665,...,3.3,0.198,-0.4,1.3,1.0,0.6,2.133278,1.015847,1.777732,0.646448
332,Shake Milton,SG,26,PHI,76,11,20.6,3.2,6.6,0.479,...,2.9,0.087,-1.0,-0.9,-2.0,0.0,1.997718,1.248574,1.664765,0.688868
31,Keita Bates-Diop,SF,27,SAS,67,42,21.7,3.5,6.9,0.508,...,2.7,0.089,0.3,-0.9,-0.6,0.5,1.878720,0.894629,3.131200,0.695822
500,Yuta Watanabe,SF,28,BRK,58,1,16.0,2.0,4.0,0.491,...,2.1,0.111,-0.4,-0.2,-0.6,0.3,1.836090,1.412377,2.040100,0.874329
294,Kevon Looney,C,26,GSW,82,70,23.9,3.0,4.7,0.630,...,8.7,0.212,0.9,1.3,2.1,2.0,8.000000,1.355932,2.857143,0.919540
91,Brandon Clarke,PF,26,MEM,56,8,19.5,4.1,6.2,0.656,...,4.5,0.199,0.8,1.8,2.5,1.3,4.343920,1.608859,2.413289,0.965316

In [101]:
budget = complete.loc[(complete['Age'] > 24) & (complete['WS'] > 5) & (complete['Salary'] < 15)].sort_values(by = ['WS'], ascending = False)
budget

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,WS,WS/48,OBPM,DBPM,BPM,VORP,Salary,S_OWS,S_DWS,S_WS
294,Kevon Looney,C,26,GSW,82,70,23.9,3.0,4.7,0.630,...,8.7,0.212,0.9,1.3,2.1,2.0,8.000000,1.355932,2.857143,0.919540
295,Brook Lopez,C,34,MIL,78,78,30.4,6.1,11.5,0.531,...,8.0,0.161,0.8,1.3,2.1,2.5,13.906976,3.391945,3.565891,1.738372
383,Mason Plumlee,C,32,TOT,79,60,26.0,4.2,6.1,0.680,...,7.9,0.185,1.2,1.0,2.2,2.2,9.080417,1.650985,3.783507,1.149420
537,Ivica Zubac,C,25,LAC,76,76,28.6,4.3,6.8,0.634,...,6.7,0.149,-1.1,0.2,-0.9,0.6,10.123457,2.664068,3.490847,1.510964
197,Josh Hart,SF-SG,27,TOT,76,52,32.3,3.6,6.8,0.529,...,6.0,0.118,-0.2,1.1,0.9,1.8,12.960000,3.410526,5.890909,2.160000
384,Jakob Poeltl,C,27,TOT,72,71,26.5,5.4,8.6,0.629,...,6.0,0.150,1.1,0.8,1.9,1.9,9.398148,2.540040,4.271885,1.566358
481,Jonas Valančiūnas,C,30,NOP,79,79,24.9,5.6,10.3,0.547,...,5.8,0.142,0.0,-0.4,-0.4,0.8,14.700000,5.250000,4.900000,2.534483
390,Bobby Portis,PF,27,MIL,70,22,26.0,5.7,11.5,0.496,...,5.3,0.139,1.2,-0.6,0.7,1.2,10.843350,4.337340,3.872625,2.045915
6,Grayson Allen,SG,27,MIL,72,70,27.4,3.4,7.7,0.440,...,5.1,0.123,-0.6,0.7,0.1,1.0,8.500000,3.035714,3.863636,1.666667
9,Kyle Anderson,PF,29,MIN,69,46,28.4,3.7,7.2,0.509,...,5.1,0.125,0.2,2.3,2.5,2.2,8.780488,3.512195,3.377111,1.721664
393,Dwight Powell,C,31,DAL,76,64,19.2,2.6,3.5,0.732,...,5.1,0.168,-1.2,0.0,-1.2,0.3,11.080125,2.915822,8.523173,2.172574